collections:
  - name: blog
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Author", name: "author", widget: "string", default: "Investipal Team"}
      - {label: "Published Date", name: "publishedDate", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["AI & Technology", "Portfolio Management", "Client Communication", "Compliance", "Industry Trends", "Best Practices", "Process Improvement"]}
      - {label: "Featured Image", name: "featuredImage", widget: "string"}
      - {label: "Featured Image Alt", name: "featuredImageAlt", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

media_folder: "public/images"
public_folder: "/images"