media:
  input: public/images
  output: /images

content:
  # Blog Posts - Simplified Configuration
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: excerpt
        label: Excerpt
        type: text
        required: true
        description: SEO description under 160 characters
      - name: author
        label: Author
        type: string
        required: true
        default: Investipal Team
      - name: authorImage
        label: Author Image
        type: string
        required: false
      - name: publishedDate
        label: Published Date
        type: date
        required: true
      - name: category
        label: Category
        type: string
        required: true
        description: Choose from AI & Technology, Portfolio Management, Client Communication, Compliance, Industry Trends, Best Practices, Process Improvement
      - name: featuredImage
        label: Featured Image
        type: image
        required: true
      - name: featuredImageAlt
        label: Featured Image Alt Text
        type: string
        required: true
      - name: featured
        label: Featured Post
        type: boolean
        required: false
        default: false
      - name: draft
        label: Draft
        type: boolean
        required: false
        default: false
      - name: seoDescription
        label: SEO Description
        type: text
        required: false
      - name: readingTime
        label: Reading Time (minutes)
        type: number
        required: false
      - name: body
        label: Content
        type: rich-text
        required: true

  # Company Data
  - name: company-data
    label: Company Data
    type: file
    path: src/data/companyData.ts
    format: code
    fields:
      - name: body
        label: Company Data (TypeScript)
        type: code
        options:
          language: typescript

  # Features Data
  - name: features-data
    label: Features Data
    type: file
    path: src/data/featuresData.ts
    format: code
    fields:
      - name: body
        label: Features Data (TypeScript)
        type: code
        options:
          language: typescript

  # Homepage
  - name: homepage
    label: Homepage
    type: file
    path: src/pages/index.astro
    format: code
    fields:
      - name: body
        label: Homepage Content (Astro)
        type: code
        options:
          language: astro

  # About Us Page
  - name: about-page
    label: About Us Page
    type: file
    path: src/pages/about-us.astro
    format: code
    fields:
      - name: body
        label: About Page Content (Astro)
        type: code
        options:
          language: astro