media:
  input: public/images
  output: /images

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: excerpt
        label: Excerpt
        type: text
        required: true
        description: SEO description under 160 characters
      - name: author
        label: Author
        type: string
        required: true
        default: Investipal Team
      - name: authorImage
        label: Author Image
        type: string
        required: false
      - name: publishedDate
        label: Published Date
        type: date
        required: true
      - name: category
        label: Category
        type: select
        required: true
        options:
          - AI & Technology
          - Portfolio Management
          - Client Communication
          - Compliance
          - Industry Trends
          - Best Practices
          - Process Improvement
      - name: tags
        label: Tags
        type: string
        list: true
        required: false
      - name: featuredImage
        label: Featured Image
        type: image
        required: true
      - name: featuredImageAlt
        label: Featured Image Alt Text
        type: string
        required: true
      - name: featured
        label: Featured Post
        type: boolean
        required: false
        default: false
      - name: draft
        label: Draft
        type: boolean
        required: false
        default: false
      - name: seoDescription
        label: SEO Description
        type: text
        required: false
      - name: readingTime
        label: Reading Time (minutes)
        type: number
        required: false
      - name: body
        label: Content
        type: rich-text
        required: true